version: "3.8"
services:
  navigator_production:
    image: "ghcr.io/gunnarsnorri/circular-city-guidance-tool:production"
    ports:
      - 3001:80
    labels:
      - "com.centurylinklabs.watchtower.scope=circular-city-guidance-tool-production"
  watchtower_production:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --scope circular-city-guidance-tool-production
    labels:
      - "com.centurylinklabs.watchtower.scope=circular-city-guidance-tool-production"
