version: "3.8"
services:
  navigator:
    image: circular-city-guidance-tool
    ports:
      - 3000:80
    labels:
      - "com.centurylinklabs.watchtower.scope=navigator"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --scope navigator
    labels:
      - "com.centurylinklabs.watchtower.scope=navigator"
