version: "3.8"
services:
  navigator:
    restart: unless-stopped
    image: "ghcr.io/gunnarsnorri/circular-city-guidance-tool:master"
    ports:
      - 3000:80
    labels:
      - "com.centurylinklabs.watchtower.scope=circular-city-guidance-tool"
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --scope circular-city-guidance-tool
    labels:
      - "com.centurylinklabs.watchtower.scope=circular-city-guidance-tool"
