services:
  navigator:
    image: "ghcr.io/gunnarsnorri/circular-city-guidance-tool:production"
    ports:
      - 3001:80
    labels:
      - "com.centurylinklabs.watchtower.scope=circular-city-guidance-tool-production"
  watchtower:
    command: --interval 300 --scope circular-city-guidance-tool-production
    labels:
      - "com.centurylinklabs.watchtower.scope=circular-city-guidance-tool-production"
