version: "3.8"
services:
  navigator:
    image: circular_city_guidance_tool
    ports:
      - 3000:80
    labels:
      - "com.centurylinklabs.watchtower.scope=circular_city_guidance_tool"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --scope circular_city_guidance_tool
    labels:
      - "com.centurylinklabs.watchtower.scope=circular_city_guidance_tool"
